version: '2.1'

services:
  apiclient:
    image: apiclient
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8090:8090
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js